image: docker:stable


variables:
  IMAGE_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  DOCKER_TLS_CERTDIR: "/certs"


services:
  - docker:stable-dind


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

    
stages:
  - build
  - deploy
  - smoke-test


build-sha:
  stage: build
  tags:
    - spi-builder
  script:
    - echo 'let appVersion = "'${CI_COMMIT_TAG:-$CI_COMMIT_SHA}'"' > ./Sources/App/Core/AppVersion.swift
    - docker build -t $IMAGE_SHA .
    - docker push $IMAGE_SHA
    

build-tag:
  stage: build
  only:
    - tags
  tags:
    - spi-builder
  script:
    # re-tag image with tag name
    - docker pull $IMAGE_SHA
    - docker tag $IMAGE_SHA $IMAGE_TAG
    - docker push $IMAGE_TAG


.deploy-common: &deploy-common
  stage: deploy
  image: docker/compose:1.25.5
  script: |
    set -eu
    VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
    # install curl and set up alias to post deployment to rollbar
    apk add --no-cache curl
    rollbar() {
      curl -H "X-Rollbar-Access-Token: $ROLLBAR_TOKEN" -X POST --data '{"environment": "'"$ENV"'", "local_username": "CI", "revision": "'"$VERSION"'", "status": "'"$1"'"}' https://api.rollbar.com/api/1/deploy
    }
    # migrate
    echo Migrating database ...
    docker-compose up -d db
    echo Deploying with SITE_URL: ${SITE_URL} ...
    env VERSION=$VERSION docker-compose run migrate
    # deploy
    env VERSION=$VERSION docker-compose up -d
    if [[ $? == 0 ]]; then
      rollbar succeeded
    else
      rollbar failed
    fi
  
  
deploy prod:
  variables:
    ENV: prod
  tags:
    - spi-prod
  <<: *deploy-common
  only:
    - tags
  
  
deploy dev:
  variables:
    ENV: dev
  tags:
    - spi-dev
  only:
    - main
  <<: *deploy-common


deploy dev (ad hoc):
  variables:
    ENV: dev
  tags:
    - spi-dev
  when: manual
  <<: *deploy-common


smoke-test:
  stage: smoke-test
  only:
    - tags
    - schedules
  tags:
    - ceres
  script: |
    rester() {
      docker run --rm -t -e base_url="$SITE_URL" -v $PWD:/host -w /host finestructure/rester:0.7.2 "$1"
    }
    echo Testing with SITE_URL: ${SITE_URL}
    rester restfiles/smoke-test.restfile
    rester restfiles/active-packages-test.restfile


db-backup (scheduled):
  stage: build
  only:
    - schedules
  tags:
    - ceres
  script: |
    FILENAME=spi_prod_$(date "+%Y-%m-%dT%H:%M:%S").dump
    echo Backing up database to file ${FILENAME}
    echo Note: This requires the appropriate SSH tunnel to be active on the runner
    env PGPASSWORD=${DATABASE_PASSWORD} pg_dump --no-owner -Fc -h localhost -p 7432 -U spi_prod spi_prod > ${FILENAME}
    echo "Moving backup file to ${DB_BACKUP_DIR}"
    mv ${FILENAME} ${DB_BACKUP_DIR}


db-backup (manual):
  stage: build
  when: manual
  tags:
    - ceres
  script: |
    FILENAME=spi_prod_$(date "+%Y-%m-%dT%H:%M:%S").dump
    echo Backing up database to file ${FILENAME}
    echo Note: This requires the appropriate SSH tunnel to be active on the runner
    env PGPASSWORD=${DATABASE_PASSWORD} pg_dump --no-owner -Fc -h localhost -p 7432 -U spi_prod spi_prod > ${FILENAME}
    echo "Moving backup file to ${DB_BACKUP_DIR}"
    mv ${FILENAME} ${DB_BACKUP_DIR}
