version: 1
builder:
  configs:
  - platform: macos-xcodebuild
    scheme: Run
  - platform: linux
    swift_version: '5.6'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.6-latest
  - platform: linux
    swift_version: '5.7'
    image: registry.gitlab.com/finestructure/spi-images:basic-5.7-latest
