version: '3.7'


x-shared: &shared
  environment:
    # set these variables via the environment or a `.env` file, which
    # docker-compose reads and uses to populate variables
    ALLOW_BUILD_TRIGGERS: ${ALLOW_BUILD_TRIGGERS}
    ALLOW_TWITTER_POSTS: ${ALLOW_TWITTER_POSTS}
    BUILD_TRIGGER_DOWNSCALING: ${BUILD_TRIGGER_DOWNSCALING}
    BUILD_TRIGGER_LIMIT: ${BUILD_TRIGGER_LIMIT}
    BUILD_TRIGGER_SLEEP: ${BUILD_TRIGGER_SLEEP}
    BUILDER_TOKEN: ${BUILDER_TOKEN}
    CHECKOUTS_DIR: ${CHECKOUTS_DIR}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
    GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
    GITLAB_PIPELINE_LIMIT: ${GITLAB_PIPELINE_LIMIT}
    GITLAB_PIPELINE_TOKEN: ${GITLAB_PIPELINE_TOKEN}
    HIDE_STAGING_BANNER: ${HIDE_STAGING_BANNER}
    LOG_LEVEL: ${LOG_LEVEL}
    METRICS_PUSHGATEWAY_URL: ${METRICS_PUSHGATEWAY_URL}
    ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
    SITE_URL: ${SITE_URL}
    TWITTER_API_KEY: ${TWITTER_API_KEY}
    TWITTER_API_SECRET: ${TWITTER_API_SECRET}
    TWITTER_ACCESS_TOKEN_KEY: ${TWITTER_ACCESS_TOKEN_KEY}
    TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
  volumes:
    - checkouts:/checkouts


services:

  server:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    ports:
      - '80:80'
    command: ["serve", "--env", "${ENV}", "--hostname", "0.0.0.0", "--port", "80"]
    deploy:
      mode: global
      update_config:
        order: start-first

  reconcile:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run reconcile --env ${ENV}; sleep ${RECONCILE_SLEEP:-120}; done"
    ]

  ingest:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run ingest --env ${ENV} --limit ${INGEST_LIMIT:-100}; sleep ${INGEST_SLEEP:-300}; done"
    ]

  analyze:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run analyze --env ${ENV} --limit ${ANALYZE_LIMIT:-25}; sleep ${ANALYZE_SLEEP:-20}; done"
    ]

  trigger_builds:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run trigger-builds --env ${ENV} --limit ${BUILD_TRIGGER_LIMIT:-1}; sleep ${BUILD_TRIGGER_SLEEP:-60}; done"
    ]
  
  migrate:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - db
    command: ["migrate", "--yes"]

  db:
    image: postgres:12.1-alpine
    sysctls:
      # NOTES: these values are needed here because docker swarm kills long running idle 
      # connections by default after 15 minutes see https://github.com/moby/moby/issues/31208
      # causing Connection reset by peer (errno: 104) leading to 500s
      # info about these values are here https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
      - net.ipv4.tcp_keepalive_intvl=600
      - net.ipv4.tcp_keepalive_probes=9
      - net.ipv4.tcp_keepalive_time=600
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}


volumes:
  db_data:
  checkouts:
