version: '3.7'


x-shared: &shared
  environment:
    # set these variables via the environment or a `.env` file, which
    # docker-compose reads and uses to populate variables
    ALLOW_BUILD_TRIGGERS: ${ALLOW_BUILD_TRIGGERS}
    ALLOW_TWITTER_POSTS: ${ALLOW_TWITTER_POSTS}
    BUILD_TRIGGER_DOWNSCALING: ${BUILD_TRIGGER_DOWNSCALING}
    BUILD_TRIGGER_LIMIT: ${BUILD_TRIGGER_LIMIT}
    BUILD_TRIGGER_SLEEP: ${BUILD_TRIGGER_SLEEP}
    BUILDER_TOKEN: ${BUILDER_TOKEN}
    CHECKOUTS_DIR: ${CHECKOUTS_DIR}
    # FIXME: remove override
    # DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_HOST: spi-prod-db-1.postgres.database.azure.com

    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    # FIXME: remove override
    # DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_USERNAME: spi_prod@spi-prod-db-1

    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    # FIXME: remove override
    # DATABASE_USE_TLS: ${DATABASE_USE_TLS}
    DATABASE_USE_TLS: 'true'

    GITHUB_TOKEN: ${GITHUB_TOKEN}
    GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
    GITLAB_PIPELINE_LIMIT: ${GITLAB_PIPELINE_LIMIT}
    GITLAB_PIPELINE_TOKEN: ${GITLAB_PIPELINE_TOKEN}
    HIDE_STAGING_BANNER: ${HIDE_STAGING_BANNER}
    LOG_LEVEL: ${LOG_LEVEL}
    METRICS_PUSHGATEWAY_URL: ${METRICS_PUSHGATEWAY_URL}
    ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
    # FIXME: remove override
    # SITE_URL: ${SITE_URL}
    SITE_URL: http://13.68.174.170

    # FIXME: re-enable
    # TWITTER_API_KEY: ${TWITTER_API_KEY}
    # TWITTER_API_SECRET: ${TWITTER_API_SECRET}
    # TWITTER_ACCESS_TOKEN_KEY: ${TWITTER_ACCESS_TOKEN_KEY}
    # TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
  volumes:
    - checkouts:/checkouts


services:

  server:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    ports:
      - '80:80'
    command: ["serve", "--env", "${ENV}", "--hostname", "0.0.0.0", "--port", "80"]
    deploy:
      mode: global
      update_config:
        order: start-first
    networks:
      - backend


  reconcile:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run reconcile --env ${ENV}; sleep ${RECONCILE_SLEEP:-120}; done"
    ]
    networks:
      - backend


  ingest:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run ingest --env ${ENV} --limit ${INGEST_LIMIT:-100}; sleep ${INGEST_SLEEP:-300}; done"
    ]
    networks:
      - backend


  analyze:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run analyze --env ${ENV} --limit ${ANALYZE_LIMIT:-25}; sleep ${ANALYZE_SLEEP:-20}; done"
    ]
    networks:
      - backend


  trigger_builds:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run trigger-builds --env ${ENV} --limit ${BUILD_TRIGGER_LIMIT:-1}; sleep ${BUILD_TRIGGER_SLEEP:-60}; done"
    ]
    networks:
      - backend


  migrate:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      restart_policy:
        condition: none
    networks:
      - backend


  # for db connections
  sshd:
    image: registry.gitlab.com/finestructure/spi-sshd:0.0.1
    entrypoint: ["/bin/bash"]
    command: ["-c", "--", "echo '${authorized_keys}' > /root/.ssh/authorized_keys && chmod 0400 /root/.ssh/authorized_keys && ssh-start ssh-server"]
    ports:
      - "2222:22"
    networks:
      - backend


volumes:
  db_data:
  checkouts:


networks:
  backend: {}
