# Operations commands
#
# docker-compose -f docker-compose.ops.yml run migrate
# docker-compose -f docker-compose.ops.yml run revert

version: '3.7'


x-shared: &shared
  environment:
    CHECKOUTS_DIR: ${CHECKOUTS_DIR}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
    LOG_LEVEL: ${LOG_LEVEL}


services:
  migrate:
    image: finestructure/spi-server:latest
    <<: *shared
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: finestructure/spi-server:latest
    <<: *shared
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
