#   Build images: docker-compose build
#      Start app: docker-compose up app

version: '3.7'

volumes:
  db_data:
  checkouts:

x-shared: &shared
  # NB: docker-compose reads env variables from `.env`, making them available
  # for db configuration (section db: below) and we also pass them on into
  # the containers via the following directive.
  env_file:
    - .env
  volumes:
    - checkouts:/checkouts

services:
  app:
    image: finestructure/spi-server:latest
    build:
      context: .
    <<: *shared
    depends_on:
      - db
    ports:
      - '8080:80'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "80"]

  db:
    image: postgres:12.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      # TODO: don't expose port
      - '5432:5432'
