version: '3.7'

# logging & monitoring visualiser

services:

  grafana:
    image: grafana/grafana:7.3.1
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_SERVER_ROOT_URL: "${GF_SERVER_ROOT_URL}"
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - app_backend


  # logging

  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/loki.yml
    configs:
      - source: loki_cfg
        target: /loki.yml
    networks:
      - app_backend


  promtail:
    image: grafana/promtail:2.0.0
    command: -config.file=/promtail.yml
    configs:
      - source: promtail_cfg
        target: /promtail.yml
    volumes:
      - /var/lib/docker/containers:/var/log
    networks:
      - app_backend


  # monitoring

  prometheus:
    image: prom/prometheus:v2.22.1
    volumes:
      - prometheus_data:/prometheus
    command: --config.file=/prometheus.yml
    configs:
      - source: prometheus_cfg
        target: /prometheus.yml
    networks:
      - app_backend


  pushgateway:
    image: prom/pushgateway:v1.3.0
    networks:
      - app_backend


configs:
  loki_cfg:
    file: ./infrastructure/loki.yml
  promtail_cfg:
    file: ./infrastructure/promtail.yml
  prometheus_cfg:
    file: ./infrastructure/prometheus.yml


volumes:
  grafana_data:
  prometheus_data:


networks:
  app_backend:
    external: true
