server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/log/*/*.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: "\\[component:\\s*(?P<component>\\w+)\\]"
      - labels:
          component:
      - drop:
          expression: "query=\"{"
