name: Continuous Integration

on: [push]

jobs:
  test-linux:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:5.2-bionic
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: spi_dev
          POSTGRES_USER: spi_dev
          POSTGRES_PASSWORD: xxx
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install docker
        run: |
          apt-get update
          apt-get install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          apt-get update
          apt-get install docker-ce -y
      - name: Run tests
        run: make test-docker
        env:
          DATABASE_HOST: postgres
          DATABASE_PORT: 5433

  # test-macos:
  #   name: Test macOS
  #   runs-on: macOS-latest
  #   services:
  #     postgres:
  #       image: postgres:12
  #       env:
  #         POSTGRES_DB: spi_dev
  #         POSTGRES_USER: spi_dev
  #         POSTGRES_PASSWORD: xxx
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Select Xcode 11.4
  #       run: sudo xcode-select -s /Applications/Xcode_11.4.app
  #     - name: Log Xcode version
  #       run: /usr/bin/xcodebuild -version
  #     - name: Run tests
  #       run: make test
  #       env:
  #         DATABASE_HOST: postgres
  #         DATABASE_PORT: 5432
